version: "2"

services:
  proxy:
    image: dockhero/caddy-proxy
    ports:
      - "80:80"
      - "80:80/udp"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_certificates:/srv
    environment:
      VIRTUAL_HOST: ${DOCKHERO_HOST}
      TARGET_URL: http://app:8080

  app:
    image: dockhero/dockhero-docs:hello

volumes:
  caddy_certificates:
    driver: local

